try {
    const a = 1;
    a  = 2
} catch (error) {
    // 1. catch必须定义错误对象error
    console.log(error);
} finally {

}